name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@2.18.0
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpcs, exussum12/coverage-checker
    - name: PHP_CodeSniffer
      run: |
        git diff $(git merge-base origin/master HEAD) > diff.txt
        phpcs --standard=ruleset.xml --report=json src/etc/inc src/opnsense > phpcs.json || true
        diffFilter --phpcs diff.txt phpcs.json
